FROM rocker/r-ver:4.1.3

LABEL author="lp23"

# Set a non-interactive frontend to avoid interactive prompts during the build
ENV DEBIAN_FRONTEND=noninteractive

# Install system dependencies for R
RUN apt-get update && apt-get upgrade -y
RUN apt-get update && apt-get install -y \
    libcurl4-openssl-dev \
    libssl-dev \
    libxml2-dev \
    libharfbuzz-dev \
    libfribidi-dev \
    libpng-dev \
    libjpeg-dev \
    libcairo2-dev \
    libtiff5-dev \
    libudunits2-dev \
    libgdal-dev \
    libgeos-dev \
    libproj-dev \
    libgmp3-dev \
    libmpfr-dev \
    libsodium-dev \
    libssh2-1-dev \
    libglpk-dev \
    libmagick++-dev \
    libpoppler-cpp-dev \
    libprotobuf-dev \
    libbz2-dev \
    liblzma-dev \
    libv8-dev \
    libxt-dev \
    libicu-dev \
    zlib1g-dev \
    libgit2-dev \
    git \
    cmake \
    clang \
    sed

RUN which sed

# Install Python and pip
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-venv

# Create virtual environment for installing jupyter
RUN python3 -m venv /opt/venv

RUN /opt/venv/bin/pip install wheel
RUN /opt/venv/bin/pip install jupyter
ENV PATH="/opt/venv/bin:$PATH"
RUN pip install jupyter

# Set the CRAN mirror
RUN Rscript -e "options(repos = list(CRAN = 'https://cran.ma.imperial.ac.uk/'))"

RUN Rscript -e "install.packages(c('pkgdown', 'systemfonts', 'textshaping', 'ragg'), dependencies = TRUE)"
RUN Rscript -e "install.packages('devtools')"

RUN Rscript -e "install.packages('readr', dependencies = TRUE)"
RUN Rscript -e "install.packages('stringr', dependencies = TRUE)"
RUN Rscript -e "install.packages('tidyr', dependencies = TRUE)"
RUN Rscript -e "install.packages('jsonlite', dependencies = TRUE)"
RUN Rscript -e "install.packages('data.table', dependencies = TRUE)"
RUN Rscript -e "install.packages('magrittr', dependencies = TRUE)"
RUN Rscript -e "install.packages('tibble', dependencies = TRUE)"
RUN Rscript -e "install.packages('patchwork', dependencies = TRUE)"

RUN Rscript -e "install.packages('ape', version = '5.6-2', dependencies = TRUE)"
RUN Rscript -e "install.packages('optparse', version = '1.7.3', dependencies = TRUE)"
RUN Rscript -e "install.packages('seqinr', version = '4.2-16', dependencies = TRUE)"
RUN Rscript -e "install.packages('VGAM', version = '1.1-7', dependencies = TRUE)"
RUN Rscript -e "install.packages('BiocManager', version = '1.30.18', dependencies = TRUE)"
RUN Rscript -e "install.packages('data.table', version = '1.14.2', dependencies = TRUE)"
RUN Rscript -e "install.packages('dplyr', version = '1.0.9', dependencies = TRUE)"
RUN Rscript -e "install.packages('ggplot2', version = '3.3.6', dependencies = TRUE)"
RUN Rscript -e "install.packages('extraDist', version = '1.10.0', dependencies = TRUE)"
RUN Rscript -e "install.packages('gridExtra', version = '2.3', dependencies = TRUE)"
RUN Rscript -e "install.packages('MASS', version = '7.3-55', dependencies = TRUE)"
RUN Rscript -e "install.packages('doParallel', version = '1.0.16', dependencies = TRUE)"
#RUN Rscript -e "install.packages('purrr', dependencies = TRUE)"
#RUN Rscript -e "install.packages('rlang', dependencies = TRUE)"
#RUN Rscript -e "install.packages('ggfun', dependencies = TRUE)"
#RUN Rscript -e "install.packages('yulab.utils', dependencies = TRUE)"
#RUN Rscript -e "install.packages('tidytree', dependencies = TRUE)"
#RUN Rscript -e "install.packages('scales', dependencies = TRUE)"
#RUN Rscript -e "install.packages('aplot', dependencies = TRUE)"

# Install Bioconductor manager and set Bioconductor version
RUN Rscript -e "BiocManager::install(version = '3.14')"

# Install Bioconductor packages
RUN Rscript -e "BiocManager::install('GenomicRanges')"
RUN Rscript -e "BiocManager::install('ggtree')"
RUN Rscript -e "BiocManager::install('Rsamtools')"

# https://bioconductor.org/packages/3.14/bioc/src/contrib/BiocGenerics_0.40.0.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/S4Vectors_0.32.4.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/IRanges_2.28.0.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/GenomeInfoDb_1.30.1.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/treeio_1.18.1.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/Rsamtools_2.10.0.tar.gz
# https://bioconductor.org/packages/3.14/bioc/src/contrib/ggtree_3.2.1.tar.gz

RUN Rscript -e "devtools::install_git('https://github.com/NickWilliamsSanger/treemut')"

RUN Rscript -e "devtools::install_git('https://github.com/lorcanpd/build_phylogeny'); library(buildphylogeny)"


# Install mpboot
RUN git clone https://github.com/diepthihoang/mpboot.git && \
    mkdir /mpboot-build && \
    cd /mpboot-build && \
    cmake ../mpboot -DIQTREE_FLAGS=avx -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && \
    make -j4

# Ensure mpboot executable is in the PATH
ENV PATH="/mpboot-build:$PATH"

# Clean up the cache to reduce image size
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# add line to ~/.bashrc to indicate LSB_DEFAULT_USERGROUP
RUN echo "export LSB_DEFAULT_USERGROUP=team274-grp" >> ~/.bashrc

# Create a directory called "data"
RUN mkdir /data

# Expose the port Jupyter will run on
EXPOSE 8888

# Set a directory for notebook files
WORKDIR /usr/src/app

# Start Jupyter Notebook
CMD ["jupyter", "notebook", "--ip=0.0.0.0", "--port=8888", "--no-browser", "--NotebookApp.token=''", "--NotebookApp.password=''"]


